import { Providers } from "@/src/app/provider";
import "@/src/app/style/tailwind.css";
import localFont from "next/font/local";

import type { Metadata } from "next";

const pretendard = localFont({
	src: "../public/font/PretendardVariable.woff2",
	variable: "--font-pretendard",
	display: "block",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Providers>
				<body className={`${pretendard.variable} font-pretendard`}>
					{children}
				</body>
			</Providers>
		</html>
	);
}
